#!/bin/bash
# This is a simple script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

if [[ "$RUBY_VERSION" == "1.8" ]]; then
  echo "ERROR: This quickstart is not compatible with Ruby 1.8"
  echo "ERROR: Please use ruby-1.9 or ruby-2.0 application type."
  exit 1
fi

rm -rf $OPENSHIFT_DATA_DIR*

mv $OPENSHIFT_REPO_DIR* $OPENSHIFT_DATA_DIR

HOME=$OPENSHIFT_REPO_DIR

curl https://raw.githubusercontent.com/creationix/nvm/v0.13.1/install.sh | bash
source ~/.nvm/nvm.sh
nvm install v0.10.24

cd $OPENSHIFT_DATA_DIR

npm install --quiet
npm run docs

cd $OPENSHIFT_DATA_DIR"client/"
npm install --quiet
./node_modules/gulp/bin/gulp.js build

mv $OPENSHIFT_DATA_DIR"server/"* $OPENSHIFT_REPO_DIR
