---
domain: stage1.mybluemix.net
disk: 246M
mem: 512M
instances: 1
applications:
- name: moonunit-stg
  host: moonunit-stg
  path: ./server
  #buildpack: https://github.com/heroku/heroku-buildpack-ruby.git
  buildpack: https://github.com/ibmdb/db2rubybuildpack.git
  services:
  - moonunit-stg-db2