# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8196dd39ae70ee86017c6fe72097e81f1feff266cd267888c05742cd988bf7edf41aa33030c0f85bdbd8b73896c973cecac173a47687d0d7ef8b7e90cea02c2

test:
  secret_key_base: 2dd6dfe2684350686d0d580a29ade0f2629474f3e0b024a342600eedbdb82de9e8de259164f9e980ac90a75a9a97d0e9e36d92f77b6f8286f8a6fb6da141b39f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
